### ISSUE TITLE
Typescript 4.3 TS2612 errors during declaration generation 

### ISSUE THREAD

**Issue by jnordberg** [Swatinem/rollup-plugin-dts#156]
The following compiles fine with TypeScript 4.3 but causes an error when generating types using dts. 

```ts
class A {
    value!: any
}

class B extends A {
    value!: number
}
```

Error is 
```
error TS2612: Property 'value' will overwrite the base property in 'A'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
```

dts with TypeScript 4.2 does not have any problem compiling the same code.

**Comment by jnordberg** [comment]
Found a workaround, in tsconfig.json set:

```json
{
    "compilerOptions": {
        "useDefineForClassFields": false,
    }
}
```

**Comment by omahesh** [comment]
> Found a workaround, in tsconfig.json set:
> 
> ```json
> {
>     "compilerOptions": {
>         "useDefineForClassFields": false,
>     }
> }
> ```

worked for me as well. thank you :)

**Comment by iamlddt** [comment]
> Found a workaround, in tsconfig.json set:
> 
> ```json
> {
>     "compilerOptions": {
>         "useDefineForClassFields": false,
>     }
> }
> ```

tks so much bro!!!
